# Generated by Django 5.2.13 on 2026-05-15 12:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email_verification_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
    ]
